server:                  #配置server
  tomcat:       #springboot乱码解决
    uri-encoding: UTF-8
  port: 8095

spring:
  devtools:      #热部署
    restart:
      enabled: true
  http:       #springboot乱码解决
    encoding:
      force: true
      charset: utf-8
      enabled: true
  thymeleaf:
    encoding: UTF-8
    cache: false
    mode: HTML5
  application:
        name: main-school
  sleuth:
      web:
        client:
          enabled: true
      sampler:
        probability: 1.0 # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
  zipkin:
    base-url: http://localhost:9411/ # 指定了 Zipkin 服务器的地址

eureka:
  client: #客户端注册进eureka服务列表内
    serviceUrl:
       defaultZone: http://localhost:8091/eureka/
  instance:
    instanceId: ${spring.cloud.client.ip-address}:${server.port}:main-school
    preferIpAddress: true     #访问路径可以显示IP地址

feign:
  hystrix:
    enabled: true

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 300000


