server:                  #配置server
  tomcat:       #springboot乱码解决
    uri-encoding: UTF-8
  port: 8096

spring:
  devtools:      #热部署
    restart:
      enabled: true
  http:       #springboot乱码解决
    encoding:
      force: true
      charset: utf-8
      enabled: true
  application:
      name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: user-operation-route
        uri: lb://user-operation
        predicates:
        - Path=/user/**
        filters:
        - RewritePath=/user/(?<path>.*), /$\{path}
      - id: main-operation-route
        uri: lb://main-operation
        predicates:
        - Path=/courseType/**
        filters:
        - RewritePath=/courseType/(?<path>.*), /$\{path}

eureka:
  client: #客户端注册进eureka服务列表内
    serviceUrl:
       defaultZone: http://localhost:8091/eureka/
  instance:
    instanceId: ${spring.cloud.client.ip-address}:${server.port}:gateway-server
    preferIpAddress: true     #访问路径可以显示IP地址

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 300000