server:                  #配置server
  tomcat:       #springboot乱码解决
    uri-encoding: UTF-8
  port: 8093

spring:
  devtools:      #热部署
    restart:
      enabled: true

eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}:main-operation
    prefer-ip-address: true     #访问路径可以显示IP地址


