server:                  #配置server
  tomcat:       #springboot乱码解决
    uri-encoding: UTF-8
  port: 8099

spring:
  http:       #springboot乱码解决
    encoding:
      force: true
      charset: utf-8
      enabled: true
  application:
      name: zipkin-server

eureka:
  client: #客户端注册进eureka服务列表内
    serviceUrl:
       defaultZone: http://localhost:8091/eureka/
  instance:
    instanceId: ${spring.cloud.client.ip-address}:${server.port}:zipkin-server
    preferIpAddress: true   #访问路径可以显示IP地址

management:
  metrics:
    web:
      server:
        auto-time-requests: false

