server:                  #配置server
  tomcat:       #springboot乱码解决
    uri-encoding: UTF-8
  port: 8091

spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true  #开启restful支持，默认只支持post个get
  http:       #springboot乱码解决
    encoding:
      force: true
      charset: utf-8
      enabled: true

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

logging:
  config: classpath:log/log4j2.xml
