server:
  port: 8097

spring:
  application:
    name: config-server
  cloud:
    config:  #http://localhost:8888/user-operation/dev
      server:
        git:
          uri: https://gitee.com/smirk/springcloud-configuration
          searchPaths: springcloud-repo

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8091/eureka/
  instance:
      instance-id: ${spring.cloud.client.ip-address}:${server.port}:config-server
      prefer-ip-address: true     #访问路径可以显示IP地址
